--
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    param_location: "{{ location }}"
    param_resource_group: "{{ resource_group }}"
    param_vm_name: "{{ vm_name }}"
  tasks:

    - name: Add OMS Agent for Linux Extension
      azure_rm_virtualmachine_extension:
        name: "OMSAgentforLinux"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.OSTCExtensions
        virtual_machine_extension_type: DSCForLinux
        type_handler_version: 2.7 
        auto_upgrade_minor_version: true
        settings:
          ExtensionAction: Register