---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    param_resource_group: "{{ resource_group }}"
    param_vm_name: "{{ vm_name }}"
    param_vm_size: "{{ vm_size }}"
    param_virtual_network: "{{ virtual_network }}"
    param_address_prefixes: "{{ address_prefixes }}"
    param_subnet_name: "{{ subnet_name }}"
    param_address_prefix: "{{ address_prefix }}"
    param_admin_username: "{{ admin_username }}"
    param_admin_password: "{{ admin_password }}"
    param_storage_type: "{{ storage_type }}"

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        location: "{{ location }}"
      register: output
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"        
        name: "{{ virtual_network }}"
        location: "{{ location }}"
        address_prefixes: "{{ address_prefixes }}"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"         
        name: "{{ subnet_name }}"
        address_prefix: "{{ address_prefix }}"
        virtual_network: "{{ virtual_network }}"
    - name: Create VMSS
      azure_rm_virtualmachine_scaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        location: westus2
        capacity: 2
        upgrade_policy: Manual
        virtual_network_name: "{{ virtual_network }}"
        subnet_name: "{{ subnet_name }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        managed_disk_type: "{{ storage_type }}"
        image:
          offer: RHEL
          publisher: Redhat
          sku: '7.4'
          version: latest
        data_disks:
          - lun: 0
            disk_size_gb: 64
            caching: ReadWrite
            managed_disk_type: "{{ storage_type }}"
