---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    param_resource_group: "{{ resource_group }}"
    param_virtual_network: "{{ virtual_network }}"
    param_address_prefixes: "{{ address_prefixes }}"
    param_address_prefix: "{{ address_prefix }}"
    param_subnet_name: "{{ subnet_name }}"

  tasks:
    - name: Create resource group if missing
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        location: "westus2"
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"        
        name: "{{ virtual_network }}"
        location: "westus2"
        address_prefixes: "{{ address_prefixes }}"
    - name: Add default subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"         
        name: "{{ subnet_name }}"
        address_prefix: "{{ address_prefix }}"
        virtual_network: "{{ virtual_network }}"