---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: "{{ param_resource_group }}"
    virtual_network: "{{ param_virtual_network }}"
    location: "{{ param_location }}"
    vm_name: "{{ param_vm_name }}"
    vm_size: "{{ param_vm_size }}"
    storage_account: "{{ param_storage_account }}"
    storage_type: "{{ param_storage_type }}"
    admin_username: "{{ param_admin_user }}"
    admin_password: "{{ param_admin_password }}"
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ param_resource_group }}"
        state: present
        location: "{{ param_location }}"
      register: output
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ param_resource_group }}"
        state: present
        name: "{{ param_virtual_network }}"
        address_prefixes_cidr: '10.128.0.0/16'
    - name: Create a subnet
      azure_rm_subnet:
        state: present
        name: "{{ param_vm_name }}.subnet"
        virtual_network_name: "{{ param_virtual_network }}"
        resource_group: "{{ param_resource_group }}"
        address_prefix_cidr: "10.128.10.0/24"
    - name: Create a network interface with private IP address and Public IP
      azure_rm_networkinterface:
        state: present
        name: "{{ param_vm_name }}.nic"        
        resource_group: "{{ param_resource_group }}"
        virtual_network_name: "{{ param_virtual_network }}"
        subnet_name: "{{ param_vm_name }}.subnet"
        security_group_name:
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ param_vm_name }}.pip"
            public_ip_allocation_method: Dynamic
            private_ip_allocation_method: Dynamic
      register: output
    - name: Create storage account
      azure_rm_storageaccount:
        name: "{{ param_storage_account }}"
        state: present
        resource_group: "{{ param_resource_group}}"        
        account_type: "{{ param_storage_type }}"
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ param_resource_group }}"
        name: "{{ param_vm_name }}"
        state: present
        vm_size: "{{ param_vm_size }}"
        managed_disk_type: "{{ param_storage_type }}"
        storage_container: "{{ param_vm_name }}.osdisk"
        storage_blob: "{{ param_vm_name }}.osdisk.vhd"
        admin_username: "{{ param_admin_user }}"
        admin_password: "{{ param_admin_password }}"        
        virtual_network_name: "{{ param_virtual_network}}"
        network_interfaces: "{{ param_vm_name }}.nic"
        image:
          offer: RHEL
          publisher: RedHat
          sku: '7.4'
          version: latest





    