---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy Linux Template
      azure_rm_deployment:
        state: present
        resource_group_name: rg-servers
        resource_group_name: "{{ resource_group_name }}"
        template: "{{ lookup('file', 'linux_template.json') }}"
        parameters: "{{ (lookup('file', 'linux_template.parameters.json') | from_json).parameters }}"