---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        location: "{{ location }}"
      register: output
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        state: present
        name: "{{ virtual_network }}"
        address_prefixes_cidr: '10.128.0.0/16'
    - name: Create a subnet
      azure_rm_subnet:
        state: present
        name: "{{ vm_name }}.subnet"
        virtual_network_name: "{{ virtual_network }}"
        resource_group: "{{ resource_group }}"
        address_prefix_cidr: "10.128.10.0/24"
    - name: Create a network interface with private IP address only (no Public IP)
      azure_rm_networkinterface:
        state: present
        name: "{{ vm_name }}.nic"        
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ virtual_network }}"
        subnet_name: "{{ vm_name }}.subnet"
        ip_configurations:
          - name: ipconfig1
            primary: True
      register: output
    - name: Create storage account
      azure_rm_storageaccount:
        name: "{{ storage_account }}"
        state: present
        resource_group: "{{ resource_group}}"        
        account_type: "{{ storage_type }}"
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        state: present
        vm_size: "{{ vm_size }}"
        managed_disk_type: "{{ storage_type }}"
        storage_container: "{{ vm_name }}.osdisk"
        storage_blob: "{{ vm_name }}.osdisk.vhd"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"        
        virtual_network_name: "{{ virtual_network}}"
        network_interfaces: "{{ vm_name }}.nic"
        image:
          offer: RHEL
          publisher: RedHat
          sku: '7.4'
          version: latest





    