---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Destroy Azure Deploy
      azure_rm_deployment:
        state: absent        
        resource_group_name: azure_test_rg

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present        
        resource_group_name: azure_test_rg
        parameters:
          adminUsername:
            value: "{{ admin_user }}"
          adminPassword:
            value: "{{ admin_password }}"
          vmName:
            value: "{{ vm_name }}"
        template: 'https://github.com/mermald/Azure_Testing/linux_template.json'
      register: azure