---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "adminUsername"
      prompt: "Enter admin username"
      private: yes
    - name: "adminPassword"
      prompt: "Enter admin password"
    - name: "vmName"
      prompt: "Enter VM hostname"

  tasks:
    - name: Deploy Linux Template
      azure_rm_deployment:
        state: present
        resource_group_name: "ansible_test_rg"
        template: "{{ lookup('file', 'linux_template.json') }}"
        parameters: "{{ (lookup('file', 'linux_template.parameters.json') | from_json).parameters }}"