---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Destroy Azure Deploy
      azure_rm_deployment:
        state: absent        
        resource_group_name: azure_test_rg

    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present        
        resource_group_name: azure_test_rg
        parameters:
          adminUsername:
            value: mermald
          adminPassword:
            value: CH@ppelle03175139
          vmName:
            value: ansibletestvm
          location:
            value: westus
        template_link: 'https://github.com/mermald/Azure_Testing/blob/master/linux_template.json'
      register: azure