---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    param_resource_group: "{{ resource_group }}"
    param_virtual_network: "{{ virtual_network }}"
    param_location: "{{ location }}"
    param_vm_name: "{{ vm_name }}"
    param_vm_size: "{{ vm_size }}"
    param_storage_account: "{{ storage_account }}"
    param_storage_type: "{{ storage_type }}"
    param_admin_username: "{{ admin_user }}"
    param_admin_password: "{{ admin_password }}"
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        location: "{{ location }}"
      register: output
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        state: present
        name: "{{ virtual_network }}"
        address_prefixes_cidr: '10.128.0.0/16'
    - name: Create a subnet
      azure_rm_subnet:
        state: present
        name: "{{ vm_name }}.subnet"
        virtual_network_name: "{{ virtual_network }}"
        resource_group: "{{ resource_group }}"
        address_prefix_cidr: "10.128.10.0/24"
    - name: Create a network interface with private IP address and Public IP
      azure_rm_networkinterface:
        state: present
        name: "{{ vm_name }}.nic"        
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ virtual_network }}"
        subnet_name: "{{ vm_name }}.subnet"
        security_group_name:
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ vm_name }}.pip"
            public_ip_allocation_method: Dynamic
            private_ip_allocation_method: Dynamic
      register: output
    - name: Create storage account
      azure_rm_storageaccount:
        name: "{{ storage_account }}"
        state: present
        resource_group: "{{ resource_group}}"        
        account_type: "{{ storage_type }}"
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        state: present
        vm_size: "{{ vm_size }}"
        managed_disk_type: "{{ storage_type }}"
        storage_container: "{{ vm_name }}.osdisk"
        storage_blob: "{{ vm_name }}.osdisk.vhd"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"        
        virtual_network_name: "{{ virtual_network}}"
        network_interfaces: "{{ vm_name }}.nic"
        image:
          offer: RHEL
          publisher: RedHat
          sku: '7.4'
          version: latest    
    - name: Create Linux Diagnostics Extension
      azure_rm_virtualmachine_extension:
        name: "IaaSDiagnostics"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.OSTCExtensions
        virtual_machine_extension_type: LinuxDiagnostic
        type_handler_version: 2.0
        auto_upgrade_minor_version: true
    - name: Add OMS Agent for Linux Extension
      azure_rm_virtualmachine_extension:
        name: "OMSAgentforLinux"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.EnterpriseCloud.Monitoring
        virtual_machine_extension_type: OmsAgentForLinux
        type_handler_version: 1.4        
        auto_upgrade_minor_version: true
        settings:
          workspaceId: "b502dca2-1ba6-491c-a446-168ffb4c3c2f"
        protected_settings: 
          workspaceKey: "3XcdU7GkPO94tNywol5D//HXO7REFrB3xNCFYALM2SVmjfavcIL6D59e9UngIr68yRigV0IjNFCd24lp5hSLEg=="







    