---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    param_resource_group: "{{ resource_group }}"
    param_virtual_network: "{{ virtual_network }}"
    param_location: "{{ location }}"
    param_vm_name: "{{ vm_name }}"
    param_vm_size: "{{ vm_size }}"    
    param_subnet_name: "{{ subnet_name }}"
    param_address_prefix: "{{ address_prefix }}"
    param_address_prefixes: "{{ address_prefixes }}"
    param_storage_account: "{{ storage_account }}"
    param_storage_type: "{{ storage_type }}"
    
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        location: "{{ location }}"
      register: output

    - name: Create storage accounts
      azure_rm_storageaccount:
        name: "{{ storage_account }}"
        state: present
        resource_group: "{{ resource_group }}"
        account_type: "{{ storage_type }}"

    - name: Create Blob container
      azure_rm_storageblob:
        resource_group: "{{ resource_group }}"
        storage_account_name: "{{ storage_account }}"
        container: "{{ vm_name }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"        
        name: "{{ virtual_network }}"
        location: "{{ location }}"
        address_prefixes: "{{ address_prefixes }}"
    
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"         
        name: "{{ subnet_name }}"
        address_prefix: "{{ address_prefix }}"
        virtual_network: "{{ virtual_network }}"
           
    - name: Create a network interface with private IP address and Public IP
      azure_rm_networkinterface:        
        name: "{{ vm_name }}.nic"        
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ virtual_network }}"
        subnet: "{{ subnet_name }}"
        private_ip_allocation_method: Dynamic        
      register: output

    - name: Create a public ip address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}.pip"
        allocation_method: Dynamic
    
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"        
        vm_size: "{{ vm_size }}"
        storage_account: "{{ storage_account }}"
        managed_disk_type: "{{ storage_type }}"
        storage_container: "{{ vm_name }}"
        storage_blob: "{{ vm_name }}.vhd"                             
        admin_username: mermald
        admin_password: P@ssword03175139        
        network_interfaces: "{{ vm_name }}.nic"
        image:
          offer: RHEL
          publisher: RedHat
          sku: '7.4'
          version: latest    
    
    - name: Add IaaS Linux Diagnostics Extension
      azure_rm_virtualmachine_extension:
        name: "IaaSDiagnostics"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.OSTCExtensions
        virtual_machine_extension_type: LinuxDiagnostic
        type_handler_version: 2.0
        auto_upgrade_minor_version: true
    
    - name: Add OMS Agent for Linux Extension
      azure_rm_virtualmachine_extension:
        name: "OMSAgentforLinux"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.EnterpriseCloud.Monitoring
        virtual_machine_extension_type: OmsAgentForLinux
        type_handler_version: 1.4        
        auto_upgrade_minor_version: true
        settings:
          workspaceId: "b502dca2-1ba6-491c-a446-168ffb4c3c2f"
        protected_settings: 
          workspaceKey: "3XcdU7GkPO94tNywol5D//HXO7REFrB3xNCFYALM2SVmjfavcIL6D59e9UngIr68yRigV0IjNFCd24lp5hSLEg=="
    
    - name: Add DSC Extension for Linux
      azure_rm_virtualmachine_extension:
        name: "DSCForLinux"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.OSTCExtensions
        virtual_machine_extension_type: DSCForLinux
        type_handler_version: 2.7 
        auto_upgrade_minor_version: true
        settings:
          ExtensionAction: "Register"
        protected_settings:
          RegistrationUrl: "https://wcus-agentservice-prod-1.azure-automation.net/accounts/6a9b862f-ad09-4b0c-8907-d4ab1fda78f6"
          RegistrationKey: "60MBW/o/yyXmrL92Ym3johoi7YcecEJ971w0AQ1Tf+eKmjLvnW6ioIUkqiK1fHJjsNwxQSoAy6HeiWmIh1lLyg=="
    
    - name: Create Custom Script Extension
      azure_rm_virtualmachine_extension:
        name: "CustomScript"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.Azure.Extensions
        virtual_machine_extension_type: CustomScript
        type_handler_version: 2.0
        settings: '{"commandToExecute": "yum update --security -y"}'
        auto_upgrade_minor_version: true







    