---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/myvars.yml
  tasks:
    - name: Create Azure Deploy
      azure_rm_resourcegroup:
        state: present
        name: "{{ resource_group }}"
        location: westus         
   # - include: "build_vm.yml"
