---
- hosts: localhost
  connection: local
  gather_facts: no
  azure_rm_deployment:
    auth_source: credential_file
  vars_files:
    - vars/myvars.yml
  tasks:
    - name: Create Azure Deploy
      azure_rm_resourcegroup:
        state: present
        name: "{{ resource_group }}"
        location: westus        
    - include: "build_vm.yml"
